name: Build Source Engine for Linux

on:
  workflow_dispatch:

jobs:
  Build:
    strategy:
        matrix:
            config:
                - {
                    platform: Linux,
                    os: ubuntu-20.04,
                    arch: x86_64,
                }
                - {
                    platform: Linux,
                    os: ubuntu-latest,
                    arch: i386
                }

    runs-on: ${{ matrix.config.os }}
    
    # Engines for Game
    # Reference：https://gist.github.com/tifasoftware/971697061ffcf783807887795d7406df
    # hl2       ->  Half-Life 2
    # episodic  ->  Half-Life 2 Episode One, Half-Life 2 Episode Two
    # hl1       ->  Half Life: Source
    # portal    ->  Portal
    env:
      games: "hl2 episodic hl1 portal"
  
    steps: 
      - name: Clone Source Code
        run: |
          git clone --recursive --depth 1 https://github.com/nillerusr/source-engine.git

      - name: Install Dependencies
        if: matrix.config.arch == 'x86_64'
        run: |
          sudo apt-get update
          sudo apt-get install -f -y libopenal-dev g++-multilib gcc-multilib libpng-dev libjpeg-dev libfreetype6-dev libfontconfig1-dev libcurl4-gnutls-dev libsdl2-dev zlib1g-dev libbz2-dev libedit-dev

      - name: Install Dependencies
        if: matrix.config.arch == 'i386'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y aptitude
          sudo aptitude install -y libopenal-dev:i386 g++-multilib gcc-multilib libpng-dev:i386 libjpeg-dev:i386 libfreetype6-dev:i386 libfontconfig1-dev:i386 libcurl4-gnutls-dev:i386 libsdl2-dev:i386 zlib1g-dev:i386 libbz2-dev:i386 libedit-dev:i386

      - name: Make Configure and Build
        run: |
          mkdir build
          cd source-engine
          
          # Build the engine
          for build_game in ${games[*]}; do
              echo "Building and installing $build_game for ${{ matrix.config.platform }} on ${{ matrix.config.arch }}..."
          
              if [ "${{ matrix.config.arch }}" == "x86_64" ]; then
                  python3 waf configure -T release --prefix='' --build-games="$build_game" --disable-warns
              elif [ "${{ matrix.config.arch }}" == "i386" ]; then
                  PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig python3 waf configure -T release --prefix='' --build-games="$build_game" --disable-warns --32bits
              fi
          
              python3 waf build
              if [ $? -ne 0 ]; then
                  echo "Build failed for $build_game"
                  exit 1
              fi
          
              python3 waf install --destdir="../build/source-engine-${build_game}-${{ matrix.config.platform }}-${{ matrix.config.arch }}"
              if [ $? -ne 0 ]; then
                  echo "Install failed for $build_game"
                  exit 1
              fi
          
              echo "$build_game build and install completed successfully."
          done

      - name: Compress and Check
        run: |
          cd build
          for build_game in ${games[*]}; do
            tar -cJf source-engine-${build_game}-${{ matrix.config.platform }}-${{ matrix.config.arch }}.tar.xz source-engine-${build_game}-${{ matrix.config.platform }}-${{ matrix.config.arch }}/*
          done

          shasum -a 256 *.tar.xz > sha256sum

          echo -e "Commit Hash: $(git log --pretty=format:'%H' -n 1)\nBuild Time: $(echo `date -u`)\nBuild by: https://github.com/Metaphorme/build-source-engine" > version.txt
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: source-engine-${{ matrix.config.platform }}-${{ matrix.config.arch }}
          path: |
            build/*.tar.xz
            build/sha256sum
            build/version.txt
