name: Build Source Engine for Android

on:
  workflow_dispatch:

jobs:
  Build:
    strategy:
        matrix:
            config:
                - {
                    platform: Android,
                    os: ubuntu-20.04,
                    arch: ARMv7A,
                }
                - {
                    platform: Android,
                    os: ubuntu-latest,
                    arch: ARMv8,
                }

    runs-on: ${{ matrix.config.os }}
    continue-on-error: true
    
    # 需要编译的引擎类型
    # 参考：https://gist.github.com/tifasoftware/971697061ffcf783807887795d7406df
    # hl2       ->  半条命2
    # episodic  ->  半条命2：第一章、半条命2：第二章（我没有测试）
    # hl1       ->  可能是半条命：起源（我没有测试）
    # portal    ->  传送门（我没有测试）
    env:
      games: "hl2 episodic hl1 portal"
  
    steps: 
      - name: Clone Source Code
        run: |
          git clone --recursive --depth 1 https://github.com/nillerusr/source-engine.git

      - name: Install Dependencies
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 11
          
          wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
          unzip android-ndk-r10e-linux-x86_64.zip

      - name: Make Configure and Build
        run: |
          export PATH="/usr/lib/llvm-11/bin:$PATH"
          export ANDROID_NDK_HOME=$PWD/android-ndk-r10e/
          export NDK_HOME=$PWD/android-ndk-r10e/

          mkdir build
          cd source-engine
          
          # 编译引擎
          for build_game in ${games[*]}; do
              echo "Building and installing $build_game for ${{ matrix.config.platform }} on ${{ matrix.config.arch }}..."
          
              if [ "${{ matrix.config.arch }}" == "ARMv7A" ]; then
                  python3 waf configure -T release --prefix='' --build-games="$build_game" --android=armeabi-v7a-hard,4.9,21 --togles
              elif [ "${{ matrix.config.arch }}" == "ARMv8" ]; then
                  python3 waf configure -T release --prefix='' --build-games="$build_game" --android=aarch64,4.9,21 --togles
              fi
          
              python3 waf build
              if [ $? -ne 0 ]; then
                  echo "Build failed for $build_game"
                  exit 1
              fi
          
              python3 waf install --destdir="../build/source-engine-${build_game}-${{ matrix.config.platform }}-${{ matrix.config.arch }}"
              if [ $? -ne 0 ]; then
                  echo "Install failed for $build_game"
                  exit 1
              fi
          
              echo "$build_game build and install completed successfully."
          done

      - name: Compress and Check
        run: |
          cd build
          for build_game in ${games[*]}; do
            tar -cJf source-engine-${build_game}-${{ matrix.config.platform }}-${{ matrix.config.arch }}.tar.xz source-engine-${build_game}-${{ matrix.config.platform }}-${{ matrix.config.arch }}/*
          done

          shasum -a 256 *.tar.xz > sha256sum

          echo -e "Commit Hash: $(git log --pretty=format:'%H' -n 1)\nBuild Time: $(echo `date -u`)\nBuild by: https://github.com/Metaphorme/build-source-engine" > version.txt
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: source-engine-${{ matrix.config.platform }}-${{ matrix.config.arch }}
          path: |
            build/*.tar.xz
            build/sha256sum
            build/version.txt
